test = {   'name': 'q4_1',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> above_eight.num_rows == 20\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> # Make sure you're columns are in the correct order!;\n>>> above_eight.sort(0).take([17])[0][0] == 'Toy Story 3'\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
