test = {   'name': 'q3_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> first_product == 6594\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> second_product == -663168\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> third_product == 66603205994\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> fourth_product == 39250\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
